version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    networks:
      - appnet
    links:
      - postgres
      - redis
    command: npm run setup && npm run start
    restart: always
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=linktrue
    networks:
      - appnet
    restart: on-failure
    volumes:
      - linktrue_pg_data:/bitnami/postgresql/

  redis:
    image: bitnami/redis:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=docker
    networks:
      - appnet
    volumes:
      - linktrue_redis_data:/bitnami/redisql/
    restart: on-failure

volumes:
  linktrue_pg_data:
  linktrue_redis_data:

networks:
  appnet:
